const birthdayData={
  name:"Ndoro Ratu Pira",
  age:"17 → 18",
  birthday:"28 September",
  mainMessage:"Happy Birthday, Pira ♡\nSelamat ulang tahun yang ke-18. Semoga di umur yang baru ini ada banyak hal baik yang datang, banyak hal yang bisa kamu banggakan, dan banyak alasan untuk tetap tersenyum. Semoga langkahmu ke depan selalu dipermudah dan semua hal yang sedang kamu perjuangkan perlahan menemukan jalannya.",
  letter:"Pira,\n\nHari ini cuma ingin menyampaikan satu hal sederhana: semoga kamu selalu baik-baik saja, di mana pun kamu berada dan apa pun yang sedang kamu jalani.\n\nKita pernah berbagi banyak cerita, tawa, dan momen yang mungkin sederhana, tapi tetap menjadi bagian dari perjalanan yang pernah kita lewati. Aku bersyukur pernah mengenalmu dan menjadi bagian kecil dari cerita itu.\n\nSekarang kamu memasuki usia 18 tahun. Semoga semakin banyak hal baik yang kamu temui, semakin kuat menghadapi hal-hal yang nggak mudah, dan semakin dekat dengan apa yang kamu cita-citakan.\n\nNggak perlu membalas apa-apa dari pesan ini. Aku cuma ingin hari ulang tahunmu punya satu hal kecil yang bisa membuatmu tersenyum.\n\nSelamat bertambah usia, Pira. Jaga diri baik-baik dan semoga tahun ini menjadi salah satu tahun yang paling berarti buatmu. ♡",
  finalMessage:"Happy 18th Birthday, Pira ♡\nSemoga cerita baru yang kamu mulai di usia ini dipenuhi hal-hal baik.\nKeep smiling. Keep growing. Keep being you."
};
const memories=[...Array.from({length:15},(_,i)=>`assets/photo${String(i+1).padStart(2,'0')}.jpg`),"assets/photo16.webp","assets/photo17.jpg","assets/photo18.jpg","assets/photo19.jpg"];
const rotated=new Set([4,14]);const $=s=>document.querySelector(s);const music=$("#music");
$("#name1").textContent=birthdayData.name;$("#name2").textContent=birthdayData.name;$("#mainMessage").textContent=birthdayData.mainMessage;$("#date").textContent=`${birthdayData.birthday} · ${birthdayData.age}`;$("#letterBody").textContent=birthdayData.letter;$("#finalText").textContent=birthdayData.finalMessage;
for(let i=0;i<42;i++){const p=document.createElement('span');p.className='particle';p.style.left=Math.random()*100+'%';p.style.setProperty('--x',(Math.random()*140-70)+'px');p.style.setProperty('--d',8+Math.random()*16+'s');p.style.animationDelay=-Math.random()*18+'s';$("#particles").appendChild(p)}
async function startMusic(){try{await music.play();$("#musicToggle").classList.add('playing');$("#musicLabel").textContent='Playing'}catch(e){$("#musicLabel").textContent='Music';console.warn('Music could not start:',e)}}$("#musicToggle").onclick=()=>music.paused?startMusic():(music.pause(),$("#musicToggle").classList.remove('playing'),$("#musicLabel").textContent='Music');
$("#openGift").onclick=async()=>{await startMusic();$("#opening").classList.add('hidden');$("#countdown").classList.remove('hidden');runCountdown()};
function runCountdown(){let n=3;const c=$("#count");const show=()=>{if(n){c.textContent=n;c.animate([{opacity:0,transform:'scale(1.35)'},{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.82)'}],{duration:950,easing:'cubic-bezier(.2,.8,.2,1)'});n--;setTimeout(show,1050)}else{setTimeout(()=>$("#word").animate([{opacity:0,transform:'scale(.85)'},{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(1.08)'}],{duration:1800}),100);setTimeout(()=>$("#heart").animate([{opacity:0,transform:'scale(.6)'},{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(1.15)'}],{duration:1600}),1850);setTimeout(()=>{$("#countdown").classList.add('hidden');['message','cardSection','memories','letter','finale'].forEach(id=>$("#"+id).classList.remove('hidden'));buildGallery();buildHeart();$("#message").scrollIntoView({behavior:'smooth'})},3450)}};show()}
$("#card").onclick=e=>{const c=e.currentTarget;c.classList.toggle('open');c.setAttribute('aria-expanded',c.classList.contains('open'))};
function buildGallery(){const g=$("#gallery");memories.forEach((src,i)=>{const card=document.createElement('article');card.className='photo'+(rotated.has(i+1)?' rot':'');card.innerHTML=`<img src="${src}" alt="Memory ${i+1}" loading="lazy"><div class="caption">memory ${String(i+1).padStart(2,'0')}</div>`;card.onclick=()=>{const l=$("#lightbox");$("#lightboxImg").src=src;$("#lightboxCaption").textContent=`memory ${String(i+1).padStart(2,'0')}`;l.classList.add('open')};g.appendChild(card)})}
$("#close").onclick=()=>$("#lightbox").classList.remove('open');$("#lightbox").onclick=e=>{if(e.target.id==='lightbox')$("#lightbox").classList.remove('open')};
function heartPoint(t){return{x:16*Math.pow(Math.sin(t),3)/18,y:-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))/18}}
function buildHeart(){const w=$("#heartCollage");memories.forEach((src,i)=>{const im=document.createElement('img');im.className='heart-photo';im.src=src;im.alt=`Heart collage photo ${i+1}`;const p=heartPoint((i/memories.length)*Math.PI*2),layer=[.78,.58,.38][i%3];im.style.left=`calc(50% + ${p.x*layer*30}% - 5%)`;im.style.top=`calc(50% + ${p.y*layer*42}% - 8%)`;im.style.setProperty('--rot',((i%5-2)*2.4)+'deg');im.style.setProperty('--sx',(Math.random()*80-40)+'vw');im.style.setProperty('--sy',(Math.random()*70-35)+'vh');w.appendChild(im);setTimeout(()=>im.classList.add('show'),700+i*120)})}
$("#replay").onclick=()=>location.reload();
